name: Bug Report
description: Melde einen Fehler
labels: [bug]
assignees: [B3sler]
body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      description: Was ist das Problem?
      placeholder: Beschreibe den Bug klar und präzise.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduktion
      description: Schritte zum Reproduzieren
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version/Commit
      placeholder: z. B. v0.1.0 oder Commit-Hash
  - type: dropdown
    id: area
    attributes:
      label: Bereich
      multiple: true
      options:
        - frontend
        - backend
        - ci
        - docs
  - type: textarea
    id: logs
    attributes:
      label: Logs/Stacktrace
      render: shell
