name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build, Lint, Test (frontend)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies (workspace root)
        run: npm ci

      - name: Lint (frontend)
        run: npm run --workspace frontend lint

      - name: Type check (frontend)
        run: npm run --workspace frontend type-check

      - name: Build (frontend)
        run: npm run --workspace frontend build

      - name: Unit tests (frontend)
        run: npm run --workspace frontend test:unit -- --run
        env:
          CI: true

  backend:
    name: Lint, Type-Check, Build, Test (backend)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies (workspace root)
        run: npm ci

      - name: Lint (backend)
        run: npm run --workspace backend lint

      - name: Type check (backend)
        run: npm run --workspace backend type-check

      - name: Build (backend)
        run: npm run --workspace backend build

      - name: Unit tests (backend)
        run: npm run --workspace backend test -- --runInBand
        env:
          CI: true
